# Generated by Django 3.0.4 on 2020-04-25 18:30

from django.db import migrations


def create_symptom_data(apps, schema_editor):
    Symptom = apps.get_model('symptom_checker', 'Symptom')
    Symptom(name="sore throat").save()
    Symptom(name="itchy rash").save()
    Symptom(name="runny nose").save()


def create_diagnosis_data(apps, schema_editor):
    Symptom = apps.get_model('symptom_checker', 'Symptom')
    sore_throat = Symptom.objects.get(name="sore throat")
    itchy_rash = Symptom.objects.get(name="itchy rash")
    runny_nose = Symptom.objects.get(name="runny nose")
    Diagnosis = apps.get_model('symptom_checker', 'Diagnosis')
    Diagnosis(name="common cold", symptom=sore_throat).save()
    Diagnosis(name="viral throat infection", symptom=sore_throat).save()
    Diagnosis(name="middle ear infection", symptom=sore_throat).save()
    Diagnosis(name="seasonal allergies", symptom=sore_throat).save()
    Diagnosis(name="strep throat", symptom=sore_throat).save()
    Diagnosis(name="mononucleosis infection", symptom=sore_throat).save()
    Diagnosis(name="bronchitis", symptom=sore_throat).save()
    Diagnosis(name="acid reflux disease", symptom=sore_throat).save()
    Diagnosis(name="acute bacterial sinusitis", symptom=sore_throat).save()
    Diagnosis(name="sunburn", symptom=itchy_rash).save()
    Diagnosis(name="irritant contact dermatitis", symptom=itchy_rash).save()
    Diagnosis(name="non-specific dermatitis (skin inflammation)", symptom=itchy_rash).save()
    Diagnosis(name="hives", symptom=itchy_rash).save()
    Diagnosis(name="benign skin growth", symptom=itchy_rash).save()
    Diagnosis(name="allergic reaction to poison ivy/oak/sumac", symptom=itchy_rash).save()
    Diagnosis(name="chronic hepatitis c", symptom=itchy_rash).save()
    Diagnosis(name="shingles (herpes zoster)", symptom=itchy_rash).save()
    Diagnosis(name="perianal skin infection", symptom=itchy_rash).save()
    Diagnosis(name=" seborrheic dermatitis", symptom=itchy_rash).save()
    Diagnosis(name="common cold", symptom=runny_nose).save()
    Diagnosis(name="chronic sinusitis", symptom=runny_nose).save()
    Diagnosis(name="non-allergic rhinitis", symptom=runny_nose).save()
    Diagnosis(name="chronic allergies", symptom=runny_nose).save()
    Diagnosis(name="normal congestion and runny nose", symptom=runny_nose).save()
    Diagnosis(name="mononucleosis infection", symptom=runny_nose).save()
    Diagnosis(name="viral infection of the larynx (voice box)", symptom=runny_nose).save()
    Diagnosis(name="chronic bronchitis", symptom=runny_nose).save()
    Diagnosis(name="hand-foot-and-mouth disease", symptom=runny_nose).save()
    Diagnosis(name="bronchiectasis", symptom=runny_nose).save()


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_checker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_symptom_data),
        migrations.RunPython(create_diagnosis_data),
    ]
